/*
 * The following code was generated by ChatGPT.
 * I would not even imagine bothering to do this manually when I have other options.
 *
 * File: fileIcons.js
 * Description: Maps common file MIME types to corresponding React Icons for use in a React project.
 * 
 * Author: Generated by ChatGPT (OpenAI), with input and modification by Neil Elkadi
 * Date: September 2024
 */

import {
  FaFilePdf,
  FaFileWord,
  FaFileExcel,
  FaFilePowerpoint,
  FaFileImage,
  FaFileVideo,
  FaFileAudio,
  FaFileArchive,
  FaFileCode,
  FaFileAlt,
  FaFileCsv,
  FaFile
} from 'react-icons/fa';

//GPT gave me these without the HTML </> which was basically unusuable. Could have re-prompted, but I just regexed it.
const fileIcons = [
  {
    fileType: "application/pdf",
    el: <FaFilePdf />
  },
  {
    fileType: "application/msword",
    el: <FaFileWord />
  },
  {
    fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    el: <FaFileWord />
  },
  {
    fileType: "application/vnd.ms-excel",
    el: <FaFileExcel />
  },
  {
    fileType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    el: <FaFileExcel />
  },
  {
    fileType: "application/vnd.ms-powerpoint",
    el: <FaFilePowerpoint />
  },
  {
    fileType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    el: <FaFilePowerpoint />
  },
  {
    fileType: "image/png",
    el: <FaFileImage />
  },
  {
    fileType: "image/jpeg",
    el: <FaFileImage />
  },
  {
    fileType: "image/gif",
    el: <FaFileImage />
  },
  {
    fileType: "image/svg+xml",
    el: <FaFileImage />
  },
  {
    fileType: "video/mp4",
    el: <FaFileVideo />
  },
  {
    fileType: "video/x-msvideo",
    el: <FaFileVideo />
  },
  {
    fileType: "audio/mpeg",
    el: <FaFileAudio />
  },
  {
    fileType: "audio/wav",
    el: <FaFileAudio />
  },
  {
    fileType: "application/zip",
    el: <FaFileArchive />
  },
  {
    fileType: "application/x-tar",
    el: <FaFileArchive />
  },
  {
    fileType: "application/json",
    el: <FaFileCode />
  },
  {
    fileType: "text/html",
    el: <FaFileCode />
  },
  {
    fileType: "text/css",
    el: <FaFileCode />
  },
  {
    fileType: "application/javascript",
    el: <FaFileCode />
  },
  {
    fileType: "text/plain",
    el: <FaFileAlt />
  },
  {
    fileType: "application/csv",
    el: <FaFileCsv />
  },
  {
    fileType: "application/xml",
    el: <FaFileCode />
  },
  {
    fileType: "application/octet-stream",
    el: <FaFile />
  },
];

//This is my code. Not GPTs. More convenient.
const getElementFromType = (filetype) => fileIcons.find(f => f.fileType === filetype)?.el ?? <FaFile />;

export default getElementFromType;
